server:
  port: 8080 # Puerto del BFF

services:
  catalog-url: http://localhost:8081/
  workorders-url: http://localhost:8082/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # URL del tenant en Entra ID
          issuer-uri: https://login.microsoftonline.com/$%7BTENANT_ID:tu-tenant-id%7D/v2.0
          # Client ID o App ID URI registrado para la API en Entra ID
          audiences: ${API_AUDIENCE:api://digitalfix-api}